// packages/web2/src/routes/login.svelte
<script lang="ts">
  import { get } from "svelte/store";
  import { loginFormState, loginFormSchema } from "$lib/auth/login_form";

  async function handleSubmit() {
    const input = get(loginFormState);
    const { error, value } = loginFormSchema.validate(input);
    console.log("LoginFormData", { error, value });

    if (!error) {
      const { login } = await import("$lib/auth/auth");
      await login(value);
      return;
    }

    // there is an error, handle it
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault="{handleSubmit}">
    <div class="form-control">
      <label for="email">Email:</label>
      <input id="email"
             name="email"
             type="email"
             placeholder="johnny.appleseed@example.com"
             required="required"
             aria-label="email"
             aria-required="true"
             bind:value={$loginFormState.email} />
    </div>

    <div class="form-control">
      <label for="password">Password:</label>
      <input id="password"
             name="password"
             type="password"
             placeholder="***************"
             required="required"
             aria-label="password"
             aria-required="true"
             bind:value={$loginFormState.password} />
    </div>

    <div class="form-control">
      <label for="rememberMe">Remember Me:</label>
      <input id="rememberMe" type="checkbox" bind:checked={$loginFormState.rememberMe}>
    </div>

    <button type="submit">Submit</button>
  </form>
</div>

// web/pages/login.tsx
import React, { useState } from "react";
import { useForm } from "react-hook-form";

import { Layout } from "@/app/components/layouts/layout";
import { Button, Label } from "@/app/components/forms/elements";
import { Link } from "@/app/components/links/link";
import { httpClient } from "@/app/lib/http_client";

export default function LoginPage() {
  const { register, handleSubmit, errors } = useForm();
  const [isSubmitting, setSubmitting] = useState(false);

  const onSubmit = async (data: any) => {
    setSubmitting(true);
    console.log(data);
    await httpClient("http://localhost:3001/auth/login", {
      body: {
        username: data.email,
        password: data.password,
      }
    }).then(({ accessToken }) => {
      console.log(accessToken);
    })
    setSubmitting(false);
  }

  return <Layout title="Login">
    <form onSubmit={handleSubmit(onSubmit)} data-test="reset-password-form" className="bg-gray-200">
      <Label data-test="login-form--email">
        <span>Email</span>
        <input type="email" defaultValue="jason@raimondi.us"  name="email" placeholder="john.doe@example.com" ref={register} />
        {errors.emailError && <span>ERROR</span>}
      </Label>
      <Label data-test="login-form--password">
        <span>Password</span>
        <input type="password" defaultValue="jasonraimondi" name="password" placeholder="******" ref={register} />
        <br />
        <Link href="/forgot_password">
          <a data-test="forgot-password-link" className="small">
            Forgot Password?
          </a>
        </Link>
        {errors.passwordError && <span>ERROR</span>}
      </Label>
      <Label data-test="login-form--remember-me">
        <input name="rememberMe" type="checkbox" ref={register} />
        <span className="inline">Remember Me</span>
        {errors.rememberMe && <span>ERROR</span>}
      </Label>
      <Button type="submit" disabled={isSubmitting}>
        <span>Submit</span>
      </Button>
    </form>
  </Layout>;
}
