// packages/web2/src/lib/auth/LoginForm.svelte
<script lang="ts">
  import { loginSchema } from "$lib/utils/forms";
  import { login } from "$lib/auth/auth";
  import { validateForm } from "$lib/utils/form_validation";

  let errors: Record<string, string> = {};

  const loginForm = {
    email: "",
    password: "",
    rememberMe: false,
  };

  async function submit() {
    errors = await validateForm({ schema: loginSchema, data: loginForm });
    if (!errors) await login(loginForm);
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault="{submit}" data-test="login-form">

    <div class="form-control">
      <label for="email">Email</label>
      {#if errors?.email}<span class="error">{errors.email}</span>{/if}
      <input id="email"
             name="email"
             type="email"
             placeholder="johnny.appleseed@example.com"
             required="required"
             aria-label="email"
             aria-required="true"
             style="margin-bottom: 0;"
             bind:value={loginForm.email} />
    </div>

    <div class="form-control">
      <label for="password">Password</label>
      {#if errors?.password}<span class="error">{errors.password}</span>{/if}
      <input id="password"
             name="password"
             type="password"
             placeholder="***************"
             required="required"
             aria-label="password"
             aria-required="true"
             bind:value={loginForm.password} />
      <a class="forgot-password" href="/forgot_password">Forgot Password?</a>
    </div>

    <div class="form-control inline">
      <label for="rememberMe">Remember Me</label>
      <input id="rememberMe" type="checkbox" bind:checked={loginForm.rememberMe}>
    </div>

    <div class="form-submit">
      <button type="submit">Submit</button>
    </div>
  </form>
</div>

<style>
  .forgot-password {
    font-size: 0.8em;
  }
</style>

// web/src/components/forms/login-form.tsx
import React from "react";
import { useForm } from "react-hook-form";

import { useAuth } from "@/app/lib/use_auth";
import { Button, FormControl, Label } from "@/app/components/forms/elements";
import { Link } from "@/app/components/links/link";

export function LoginForm() {
  const { register, handleSubmit, formState } = useForm({ mode: "onChange" });

  const { handleLogin } = useAuth();

  return (
    <form onSubmit={handleSubmit(handleLogin)} data-test="login-form">
      <h1>Login</h1>
      <FormControl>
        <Label id="login-form--email">Email</Label>
        <input
          type="email"
          id="login-form--email"
          placeholder="john.doe@example.com"
          {...register("email", { required: true })}
        />
        {formState.errors.emailError && <span>ERROR</span>}
      </FormControl>

      <FormControl>
        <Label id="login-form--password">Password</Label>
        <input
          type="password"
          id="login-form--password"
          placeholder="******"
          {...register("password", { required: true })}
        />
        <Link href="/forgot_password" data-test="forgot-password-link">
          <small>Forgot Password?</small>
        </Link>
        {formState.errors.passwordError && <span>ERROR</span>}
      </FormControl>

      <FormControl>
        <Label id="login-form--remember">Remember Me</Label>
        <input id="login-form--remember" type="checkbox" {...register("rememberMe")} />
        {formState.errors.rememberMe && <span>ERROR</span>}
      </FormControl>

      <Button data-test="login-form--submit" disabled={formState.isDirty && !formState.isValid}>
        Submit
      </Button>
    </form>
  );
}
