// packages/web2/src/lib/auth/LoginForm.svelte
<script lang="ts">
  import { loginSchema } from "$lib/utils/forms";
  import { login } from "$lib/auth/auth";
  import { validateForm } from "$lib/utils/form_validation";

  let errors: Record<string, string> = {};

  const loginForm = {
    email: "",
    password: "",
    rememberMe: false,
  };

  async function submit() {
    errors = await validateForm({ schema: loginSchema, data: loginForm });
    if (!errors) await login(loginForm);
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault="{submit}" data-test="login-form">

    <div class="form-control">
      <label for="email">Email</label>
      {#if errors?.email}<span class="error">{errors.email}</span>{/if}
      <input id="email"
             name="email"
             type="email"
             placeholder="johnny.appleseed@example.com"
             required="required"
             aria-label="email"
             aria-required="true"
             style="margin-bottom: 0;"
             bind:value={loginForm.email} />
    </div>

    <div class="form-control">
      <label for="password">Password</label>
      {#if errors?.password}<span class="error">{errors.password}</span>{/if}
      <input id="password"
             name="password"
             type="password"
             placeholder="***************"
             required="required"
             aria-label="password"
             aria-required="true"
             bind:value={loginForm.password} />
      <a class="forgot-password" href="/forgot_password">Forgot Password?</a>
    </div>

    <div class="form-control inline">
      <label for="rememberMe">Remember Me</label>
      <input id="rememberMe" type="checkbox" bind:checked={loginForm.rememberMe}>
    </div>

    <div class="form-submit">
      <button type="submit">Submit</button>
    </div>
  </form>
</div>

<style>
  .forgot-password {
    font-size: 0.8em;
  }
</style>

// web/src/components/forms/login_form.tsx
import React from "react";
import { ErrorMessage, Field, Form, Formik } from "formik";
import { Button, Label } from "@/app/components/forms/elements";
import { Link } from "@/app/components/links/link";
import { validEmail } from "@/app/pages/register";

export type LoginFormData = {
  email: string;
  password: string;
  rememberMe: boolean;
};

type Props = {
  handleSubmit: any;
};

const LoginForm = ({ handleSubmit }: Props) => {
  const handleValidate = (values: LoginFormData) => {
    let errors: any = {};
    if (!values.email) {
      errors.email = "Required";
    } else if (!validEmail.test(values.email)) {
      errors.email = "Invalid email address";
    }
    return errors;
  };

  return (
    <Formik<LoginFormData>
      initialValues={{ email: "", password: "", rememberMe: false }}
      validate={handleValidate}
      onSubmit={handleSubmit}
    >
      {({ isSubmitting, status, values }) => (
        <Form data-test="login-form">
          <p>{status}</p>
          <Label data-test="login-form--email">
            <span>Email</span>
            <Field type="email" name="email" placeholder="john.doe@example.com" />
            <ErrorMessage data-test="email-error" name="email" component="div" />
          </Label>
          <Label data-test="login-form--password">
            <span>Password</span>
            <Field type="password" name="password" placeholder="******" />
            <br />
            <Link href="/forgot_password">
              <a data-test="forgot-password-link" className="small">
                Forgot Password?
              </a>
            </Link>
            <ErrorMessage data-test="password-error" name="password" component="div" />
          </Label>
          <Label data-test="login-form--remember-me">
            <Field name="rememberMe" type="checkbox" checked={values.rememberMe} component={Checkbox} />
            <span className="inline">Remember Me</span>
            <ErrorMessage data-test="remember-me" name="remember-me" component="div" />
          </Label>
          <Button type="submit" disabled={isSubmitting}>
            <span>Submit</span>
          </Button>
        </Form>
      )}
    </Formik>
  );
};

function Checkbox({ field, type, checked }: any) {
  return <input {...field} type={type} checked={checked} />;
}

export default LoginForm;
