// web/src/components/forms/reset-password-form.tsx
import { useForm } from "react-hook-form";
import React, { useState } from "react";
import { graphQLSdk } from "@/app/lib/api_sdk";
import { Button, FormControl, Label } from "@/app/components/forms/elements";
import { useRouter } from "next/router";
import { useNotify } from "use-notify-rxjs";

type ResetPasswordFormData = { password: string };

export function ResetPasswordForm({ email, token }: { email: string; token: string }) {
  const { register, handleSubmit, formState } = useForm();
  const router = useRouter();
  const notify = useNotify();

  const [isSubmitting, setSubmitting] = useState(false);

  const onSubmit = async (foo: ResetPasswordFormData) => {
    await graphQLSdk.ValidateForgotPasswordToken({ data: { token, email } });
    const { data, errors } = await graphQLSdk.UpdatePasswordFromToken({
      data: { password: foo.password, token, email },
    });

    if (!errors && data) {
      const { accessToken, user } = data.updatePasswordFromToken;
      notify.info(accessToken);
      notify.info(user.email);
    }

    notify.info("We should auto login the user here");
    setSubmitting(false);
    await router.replace("/");
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} data-test="reset-password-form">
      <h1>Reset Password</h1>

      <FormControl>
        <Label id="reset-password-form--password">Password</Label>
        {formState.errors.password}
        <input
          type="password"
          id="reset-password-form--password"
          placeholder="enter a secure password"
          {...register("password", { required: true, minLength: 8 })}
        />
      </FormControl>

      <Button data-test="reset-password-form--submit" type="submit" disabled={isSubmitting}>
        Submit
      </Button>
    </form>
  );
}

// modules/web/src/components/forms/ResetPasswordForm.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { validateForm } from "@jmondi/form-validator";
  import { graphQLSdk } from "$lib/api/api_sdk";
  import { updatePasswordFromTokenSchema } from "$ui/forms/schema";
  import { setAccessToken } from "$lib/auth/auth";
  import { notify } from "$ui/notifications/notification.service";

  export let email: string;
  export let token: string;

  let errors: Record<string, string> | undefined;

  const formData = {
    password: "",
  };

  async function submit() {
    const input = { email, token, password: formData.password };
    errors = await validateForm({ schema: updatePasswordFromTokenSchema, data: input });
    if (!errors) {
      const { updatePasswordFromToken } = await graphQLSdk.UpdatePasswordFromToken({ input });
      setAccessToken(updatePasswordFromToken.accessToken);
      notify.success("It sent!");
      await goto("/app");
    }
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault={submit} data-test="reset-password-form">
    <div class="form-control">
      <label for="password">Password</label>
      {#if errors?.password}<span class="error">{errors.password}</span>{/if}
      <input
        id="password"
        name="password"
        type="password"
        placeholder="********"
        aria-label="password"
        aria-required="true"
        bind:value={formData.password}
      />
    </div>
    <div class="form-submit">
      <button id="submit" type="submit">Submit</button>
    </div>
  </form>
</div>
