// packages/web2/src/routes/__layout.svelte
<Notifications />

<!--<Header />-->

<main>
  <slot />
</main>

<DebugBar />

<style lang="postcss">
  main {
    height: 100%;
  }
</style>

<script lang="ts">
  import "normalize.css/normalize.css";
  import "../app.pcss";

  import Notifications from "$lib/notifications/Notifications.svelte";
  // import Header from "$lib/layouts/Header.svelte";
  import DebugBar from "$lib/debug_bar/DebugBar.svelte";

  // async function checkAuth() {
  //   const { notify } = import("$lib/notifications/notification.service");
  //   const { isAuthenticated, refreshToken } = import("$lib/auth/auth");
  //   const isExpired = !isAuthenticated();
  //
  //   if (isPrivate && isExpired) {
  //     notify.info("is private and is expired, running token refresh");
  //     if (await refreshToken()) {
  //       notify.info("It refreshed successfully");
  //     } else {
  //       const { goto } = import("$app/navigation");
  //       await goto("/login");
  //     }
  //   }
  // }
</script>

// packages/web/src/components/layouts/layout.tsx
import classnames from "classnames";
import Head from "next/head";
import { useRouter } from "next/router";
import { FC, useEffect, useMemo } from "react";

import { Notify } from "@/app/components/layouts/partials/notify";
import { Header } from "@/app/components/layouts/partials/header";
import { useAuth } from "@/app/lib/use_auth";
import { DebugBar } from "@/app/components/debug/debug";

import el from "./layout.module.css";
import { notifyService } from "use-notify-rxjs";

export const Layout: FC<{ title?: string; isPrivate?: boolean }> = ({
  children,
  title = "Scratchy Title",
  isPrivate = false,
}) => {
  const auth = useAuth();
  const router = useRouter();

  useEffect(() => void checkAuth(), []);

  const isExpired = useMemo(() => !auth.isAuthenticated, [auth.accessToken]);

  async function checkAuth() {
    if (isPrivate && isExpired) {
      notifyService.info("is private and is expired, running token refresh");
      // this line is racing against the useMe query line
      if (await auth.refreshToken()) {
        notifyService.info("It refreshed successfully");
      } else {
        await router.push("/login");
      }
    }
  }

  let body;

  if (isPrivate && isExpired) {
    console.log("unauthorized");
    body = <p>Unauthorized</p>;
  } else {
    body = children;
  }

  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <title>{title}</title>
      </Head>
      <Header />
      <Notify />
      <main className={classnames("container padded center", el.main)}>{body}</main>
      {process.env.NODE_ENV === "development" && <DebugBar />}
    </>
  );
};
