// web/src/components/layouts/partials/header.tsx
import React from "react";
import styled from "@emotion/styled";
import { css } from "@emotion/core";

import { Link } from "@/app/components/links/link";
import { colors } from "@/styles/theme";
import { useAuth } from "@/app/lib/use_auth";

export function Header() {
  const { isAuthenticated } = useAuth();

  return (
    <header>
      <nav
        css={css`
          display: flex;
        `}
      >
        <Link href="/">
          <NavAnchor>Home</NavAnchor>
        </Link>
        {isAuthenticated() ? (
          <>
            <Link href="/app/dashboard">
              <NavAnchor>Dashboard</NavAnchor>
            </Link>
            <Link href="/app/profile">
              <NavAnchor>Profile</NavAnchor>
            </Link>
            <Link href="/logout">
              <NavAnchor data-test="logout-link">Logout</NavAnchor>
            </Link>
          </>
        ) : (
          <>
            <Link href="/app/profile">
              <NavAnchor data-test="register-link">RESTRICTED</NavAnchor>
            </Link>
            <Link href="/register">
              <NavAnchor data-test="register-link">Register</NavAnchor>
            </Link>
            <Link href="/login">
              <NavAnchor data-test="login-link">Login</NavAnchor>
            </Link>
          </>
        )}
      </nav>
    </header>
  );
};

const NavAnchor = styled.a`
  color: ${colors.gray["100"]};
  font-weight: 500;
  padding: 0.5rem 0;

  &:hover,
  &:active {
    color: ${colors.gray["400"]};
  }

  &:after {
    content: "|";
    color: ${colors.black};
    text-decoration: none;
    padding: 0 2px;
  }
  &:last-child:after {
    content: "";
    padding: 0;
  }
`;

// web/src/components/layouts/Header.svelte
<script lang="ts">
  import { currentUserStore } from "$lib/auth/current_user";
</script>

<header>
  <nav class="nav">
    <ul class="left">
      <li><a href="/" data-test="link--home">Home</a></li>
      {#if $currentUserStore?.isAdmin}<li><a href="/admin" data-test="link--admin" style="color: var(--colors-red-500);">Admin</a></li>{/if}
    </ul>
    <ul class="right">
      {#if $currentUserStore}
        <li><a href="/app" data-test="link--dashboard">Dashboard</a></li>
        <li><a href="/app/profile" data-test="link--profile">Profile</a></li>
        <li><a href="/logout" data-test="link--logout">Logout</a></li>
      {:else}
        <li><a href="/register" data-test="link--register">Register</a></li>
        <li><a href="/login" data-test="link--login">Login</a></li>
      {/if}
    </ul>
  </nav>
</header>

<style lang="postcss">
  header {
    overflow-x: auto;
  }
  .nav {
    border-bottom: 1px solid var(--colors-gray-400);
    display: flex;
  }

  .left {
    flex: 1;
  }

  .left,
  .right {
    margin: 0.4em;
    display: flex;
    li {
      margin-right: 1em;
      &:last-child {
        margin-right: 0;
      }
    }
  }
</style>
