// web/src/components/forms/forgot-password-form.tsx
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import React, { useState } from "react";

import { graphQLSdk } from "@/app/lib/api_sdk";
import { Button, FormControl, Label } from "@/app/components/forms/elements";

export const validEmailRegex = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;

export function ForgotPasswordForm() {
  const router = useRouter();

  const {
    register,
    handleSubmit,

    formState: { errors },
  } = useForm();

  const [isSubmitting, setSubmitting] = useState(false);

  const onSubmit = async (data: any) => {
    await graphQLSdk.SendForgotPasswordEmail({ email: data.email });
    await router.push("/");
    setSubmitting(false);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} data-test="forgot-password-form">
      <h1>Forgot Password?</h1>
      <FormControl>
        <Label id="forgot-password-form--email">Email</Label>
        <input
          type="email"
          {...register("email", { required: true, pattern: validEmailRegex })}
          id="forgot-password-form--email"
          placeholder="john.doe@example.com"
        />
        {errors.email}
      </FormControl>
      <Button data-test="forgot-password-form--submit" type="submit" disabled={isSubmitting}>
        Submit
      </Button>
    </form>
  );
}

// packages/web2/src/lib/auth/ForgotPasswordForm.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { graphQLSdk } from "$lib/api/api_sdk";
  import { forgotPasswordSchema } from "$lib/utils/forms";
  import { validateForm } from "$lib/utils/form_validation";
  import { notify } from "$lib/notifications/notification.service";

  let errors: Record<string, string> = {};
  const formData = {
    email: "",
  };

  async function submit() {
    errors = await validateForm({ schema: forgotPasswordSchema, data: formData });
    if (!errors) {
      await graphQLSdk.SendForgotPasswordEmail({ email: formData.email });
      notify.success("It sent!");
      await goto("/");
    }
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault="{submit}" data-test="forgot-password-form">
    <div class="form-control">
      <label for="email">Email</label>
      {#if errors?.email}<span class="error">{errors.email}</span>{/if}
      <input id="email"
             name="email"
             type="email"
             placeholder="johnny.appleseed@example.com"
             required="required"
             aria-label="email"
             aria-required="true"
             bind:value={formData.email} />
    </div>

    <div class="form-submit">
      <button type="submit">Submit</button>
      <a class="back" href="/login">Back to Login</a>
    </div>
  </form>
</div>
