// web/src/components/forms/forgot-password-form.tsx
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import React, { useState } from "react";

import { graphQLSdk } from "@/app/lib/api_sdk";
import { Button, FormControl, Label } from "@/app/components/forms/elements";

export const validEmailRegex = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;

export function ForgotPasswordForm() {
  const router = useRouter();

  const {
    register,
    handleSubmit,

    formState: { errors },
  } = useForm();

  const [isSubmitting, setSubmitting] = useState(false);

  const onSubmit = async (data: any) => {
    await graphQLSdk.SendForgotPasswordEmail({ email: data.email });
    await router.push("/");
    setSubmitting(false);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} data-test="forgot-password-form">
      <h1>Forgot Password?</h1>
      <FormControl>
        <Label id="forgot-password-form--email">Email</Label>
        <input
          type="email"
          {...register("email", { required: true, pattern: validEmailRegex })}
          id="forgot-password-form--email"
          placeholder="john.doe@example.com"
        />
        {errors.email}
      </FormControl>
      <Button data-test="forgot-password-form--submit" type="submit" disabled={isSubmitting}>
        Submit
      </Button>
    </form>
  );
}

// packages/web2/src/lib/auth/forgot_password_form.svelte
<script lang="ts">
  import { forgotPasswordForm } from "$lib/utils/forms";
  import { validateForm } from "$lib/utils/form_validation";
  import { graphQLSdk } from "$lib/api/api_sdk";

  let errors: Record<string, string> = {};
  const formData = {
    email: "",
  };

  async function submit() {
    errors = await validateForm({ schema: forgotPasswordForm, data: formData });
    if (!errors) await graphQLSdk.SendForgotPasswordEmail({ email: formData.email });
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault="{submit}">
    <div class="form-control">
      <label for="email">Email:</label>
      {#if errors?.email}<span class="error">{errors.email}</span>{/if}
      <input id="email"
             name="email"
             type="email"
             placeholder="johnny.appleseed@example.com"
             required="required"
             aria-label="email"
             aria-required="true"
             bind:value={formData.email} />
    </div>
    <button type="submit">Submit</button>
  </form>
</div>
