// web/src/components/forms/register-form.tsx
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import React, { useState } from "react";

import { graphQLSdk } from "@/app/lib/api_sdk";
import { Button, FormControl, Label } from "@/app/components/forms/elements";
import { validEmailRegex } from "@/app/components/forms/forgot-password-form";

export type RegisterFormData = {
  email: string;
  password: string;
  firstName?: string;
  lastName?: string;
};

export function RegisterForm() {
  const router = useRouter();

  const { register, handleSubmit, formState } = useForm();

  const [status, setStatus] = useState<string>();
  const [isSubmitting, setSubmitting] = useState(false);

  const onSubmit = async (data: RegisterFormData) => {
    setSubmitting(true);
    try {
      await graphQLSdk.Register({ data });
      setSubmitting(false);
      await router.push("/register/success");
    } catch (e) {
      setStatus(e.message);
    }
    setSubmitting(false);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} data-test="register-form">
      <h1>Register</h1>
      {status && <span className="bg-red-500 text-white text-center px-6 py-1 my-2 rounded">{status}</span>}
      <FormControl>
        <Label id="register-form--email">Email</Label>
        <input
          type="email"
          id="register-form--email"
          placeholder="john.doe@example.com"
          {...register("email", { required: true, pattern: validEmailRegex })}
        />
        {formState.errors.email && <span>{formState.errors.email}</span>}
      </FormControl>

      <FormControl>
        <Label id="register-form--password">Password</Label>
        <input
          type="password"
          id="register-form--password"
          placeholder="**************"
          {...register("password", { required: true })}
        />
        {formState.errors.password && <span>{formState.errors.password}</span>}
      </FormControl>

      <FormControl>
        <Label id="register-form--first">First Name</Label>
        <input
          type="text"
          id="register-form--first"
          placeholder="John"
          {...register("firstName", { required: true })}
        />
        {formState.errors.firstName && <span>{formState.errors.firstName}</span>}
      </FormControl>

      <FormControl>
        <Label id="register-form--last">Last Name</Label>
        <input type="text" id="register-form--last" placeholder="Doe" {...register("lastName", { required: true })} />
        {formState.errors.lastName && <span>{formState.errors.lastName}</span>}
      </FormControl>

      <Button type="submit" disabled={isSubmitting}>
        Submit
      </Button>
    </form>
  );
}

// packages/web2/src/lib/auth/register_form.svelte
<script lang="ts">
  import { registerFormSchema } from "$lib/utils/forms";
  import { validateForm } from "$lib/utils/form_validation";
  import { graphQLSdk } from "$lib/api/api_sdk";

  // errors are key value, where key is the form name, and value is the error message
  let errors: Record<string, string> = {};

  const data = {
    email: "",
    password: "",
    firstName: "",
    lastName: "",
  };

  async function submit() {
    errors = await validateForm({ schema: registerFormSchema, data });
    if (!errors) await graphQLSdk.Register({ input: data });
  }
</script>

<div class="centered-form">
  <form on:submit|preventDefault="{submit}">

    <div class="form-control">
      <label for="firstName">First:</label>
      {#if errors?.firstName}<span class="error">{errors.firstName}</span>{/if}
      <input id="firstName"
             name="firstName"
             type="text"
             placeholder="Johnny"
             required="required"
             aria-label="firstName"
             aria-required="true"
             bind:value={data.firstName} />
    </div>

    <div class="form-control">
      <label for="lastName">Last:</label>
      {#if errors?.lastName}<span class="error">{errors.lastName}</span>{/if}
      <input id="lastName"
             name="lastName"
             type="text"
             placeholder="Appleseed"
             required="required"
             aria-label="lastName"
             aria-required="true"
             bind:value={data.lastName} />
    </div>

    <div class="form-control">
      <label for="email">Email:</label>
      {#if errors?.email}<span class="error">{errors.email}</span>{/if}
      <input id="email"
             name="email"
             type="email"
             placeholder="johnny.appleseed@example.com"
             required="required"
             aria-label="email"
             aria-required="true"
             bind:value={data.email} />
    </div>

    <div class="form-control">
      <label for="password">Password:</label>
      {#if errors?.password}<span class="error">{errors.password}</span>{/if}
      <input id="password"
             name="password"
             type="password"
             placeholder="***************"
             required="required"
             aria-label="password"
             aria-required="true"
             bind:value={data.password} />
    </div>

    <button type="submit">Submit</button>
  </form>
</div>

<style>
  .error {
      font-size: 0.8em;
  }
</style>
