// packages/web2/src/lib/layouts/Header.svelte
<script lang="ts">
  const isAuthenticated = Math.random() > 0.5;

  type MenuItem = {
    name: string;
    href: string;
    dataTest: string;
  };

  const leftMenu: MenuItem[] = [{ name: "Home", href: "/", dataTest: "link--home" }];
  const rightMenu: MenuItem[] = [];

  if (isAuthenticated) {
    leftMenu.push(
      { name: "Dashboard", href: "/app/dashboard", dataTest: "link--dashboard" },
      { name: "Profile", href: "/app/profile", dataTest: "link--profile" },
    );
    rightMenu.push({ name: "Logout", href: "/logout", dataTest: "link--logout" });
  } else {
    leftMenu.push();
    rightMenu.push(
      { name: "Register", href: "/register", dataTest: "link--register" },
      { name: "Login", href: "/login", dataTest: "link--login" },
    );
  }
</script>

<header class="container center padded">
  <nav class="nav">
    <ul class="left">
      {#each leftMenu as l}
        <li>
          <a href={l.href} data-test={l.dataTest}>{l.name}</a>
        </li>
      {/each}
    </ul>
    <ul class="right">
      {#each rightMenu as r}
        <li>
          <a href={r.href} data-test={r.dataTest}>{r.name}</a>
        </li>
      {/each}
    </ul>
  </nav>
</header>

<style lang="postcss">
    .nav {
        display: flex;
        padding: 0 0 0.5em;
        margin-bottom: 0.5em;
        border-bottom: 1px solid var(--colors-gray-400);
    }

    .left {
        flex: 1;
    }

    .left,
    .right {
        display: flex;
        li {
            margin-right: 1em;
            &:last-child {
                margin-right: 0;
            }
        }
    }
</style>

// web/src/components/layouts/partials/header.tsx
import React from "react";

import { Link } from "@/app/components/links/link";
import { useAuth } from "@/app/lib/use_auth";

import el from "./header.module.css";

type MenuItem = {
  name: string;
  href: string;
  dataTest: string;
};

export function Header() {
  const { isAuthenticated } = useAuth();
  const leftMenu: MenuItem[] = [{ name: "Home", href: "/", dataTest: "link--home" }];
  const rightMenu: MenuItem[] = [];

  if (isAuthenticated()) {
    leftMenu.push(
      { name: "Dashboard", href: "/app/dashboard", dataTest: "link--dashboard" },
      { name: "Profile", href: "/app/profile", dataTest: "link--profile" },
    );
    rightMenu.push({ name: "Logout", href: "/logout", dataTest: "link--logout" });
  } else {
    leftMenu.push();
    rightMenu.push(
      { name: "Register", href: "/register", dataTest: "link--register" },
      { name: "Login", href: "/login", dataTest: "link--login" },
    );
  }

  return (
    <header className="container center padded">
      <nav className={el.nav}>
        <ul className={el.left}>
          {leftMenu.map(l => (
            <li key={l.name}>
              <Link href={l.href} data-test={l.dataTest}>
                {l.name}
              </Link>
            </li>
          ))}
        </ul>
        <ul className={el.right}>
          {rightMenu.map(l => (
            <li key={l.name}>
              <Link href={l.href} data-test={l.dataTest}>
                {l.name}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}
